/* tslint:disable */
/* eslint-disable */
/*
 * StatusCake API
 *
 * Copyright (c) 2023
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * API version: 1.2.0
 * Contact: support@statuscake.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

import { exists, mapValues } from '../runtime';
import {
  HeartbeatTestOverview,
  HeartbeatTestOverviewFromJSON,
  HeartbeatTestOverviewFromJSONTyped,
  HeartbeatTestOverviewToJSON,
} from './HeartbeatTestOverview';
import {
  Pagination,
  PaginationFromJSON,
  PaginationFromJSONTyped,
  PaginationToJSON,
} from './Pagination';

/**
 *
 * @export
 * @interface HeartbeatTests
 */
export interface HeartbeatTests {
  /**
   * List of heartbeat checks
   * @type {Array<HeartbeatTestOverview>}
   * @memberof HeartbeatTests
   */
  data: Array<HeartbeatTestOverview>;
  /**
   *
   * @type {Pagination}
   * @memberof HeartbeatTests
   */
  metadata: Pagination;
}

export function HeartbeatTestsFromJSON(json: any): HeartbeatTests {
  return HeartbeatTestsFromJSONTyped(json, false);
}

export function HeartbeatTestsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HeartbeatTests {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(HeartbeatTestOverviewFromJSON),
    metadata: PaginationFromJSON(json['metadata']),
  };
}

export function HeartbeatTestsToJSON(value?: HeartbeatTests | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: (value.data as Array<any>).map(HeartbeatTestOverviewToJSON),
    metadata: PaginationToJSON(value.metadata),
  };
}
