/* tslint:disable */
/* eslint-disable */
/*
 * StatusCake API
 *
 * Copyright (c) 2023
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * API version: 1.1.0
 * Contact: support@statuscake.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PagespeedTestStats
 */
export interface PagespeedTestStats {
  /**
   * Latest recorded filesize (kb)
   * @type {number}
   * @memberof PagespeedTestStats
   */
  filesize: number;
  /**
   * Whether the latest check has an issue
   * @type {boolean}
   * @memberof PagespeedTestStats
   */
  hasIssue: boolean;
  /**
   * Latest recorded loadtime (ms)
   * @type {number}
   * @memberof PagespeedTestStats
   */
  loadtime: number;
  /**
   * Latest recorded request count
   * @type {number}
   * @memberof PagespeedTestStats
   */
  requests: number;
  /**
   * Latest recorded issue
   * @type {string}
   * @memberof PagespeedTestStats
   */
  latestIssue?: string;
}

export function PagespeedTestStatsFromJSON(json: any): PagespeedTestStats {
  return PagespeedTestStatsFromJSONTyped(json, false);
}

export function PagespeedTestStatsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PagespeedTestStats {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    filesize: json['filesize'],
    hasIssue: json['has_issue'],
    loadtime: json['loadtime'],
    requests: json['requests'],
    latestIssue: !exists(json, 'latest_issue')
      ? undefined
      : json['latest_issue'],
  };
}

export function PagespeedTestStatsToJSON(
  value?: PagespeedTestStats | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    filesize: value.filesize,
    has_issue: value.hasIssue,
    loadtime: value.loadtime,
    requests: value.requests,
    latest_issue: value.latestIssue,
  };
}
