/* tslint:disable */
/* eslint-disable */
/*
 * StatusCake API
 *
 * Copyright (c) 2022
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * API version: 1.0.0-beta.2
 * Contact: support@statuscake.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

import { exists, mapValues } from '../runtime';
import {
  PagespeedTestHistoryDataAggregatedFilesize,
  PagespeedTestHistoryDataAggregatedFilesizeFromJSON,
  PagespeedTestHistoryDataAggregatedFilesizeFromJSONTyped,
  PagespeedTestHistoryDataAggregatedFilesizeToJSON,
} from './PagespeedTestHistoryDataAggregatedFilesize';
import {
  PagespeedTestHistoryDataAggregatedLoadtime,
  PagespeedTestHistoryDataAggregatedLoadtimeFromJSON,
  PagespeedTestHistoryDataAggregatedLoadtimeFromJSONTyped,
  PagespeedTestHistoryDataAggregatedLoadtimeToJSON,
} from './PagespeedTestHistoryDataAggregatedLoadtime';
import {
  PagespeedTestHistoryDataAggregatedRequests,
  PagespeedTestHistoryDataAggregatedRequestsFromJSON,
  PagespeedTestHistoryDataAggregatedRequestsFromJSONTyped,
  PagespeedTestHistoryDataAggregatedRequestsToJSON,
} from './PagespeedTestHistoryDataAggregatedRequests';

/**
 * Aggregated results
 * @export
 * @interface PagespeedTestHistoryDataAggregated
 */
export interface PagespeedTestHistoryDataAggregated {
  /**
   *
   * @type {PagespeedTestHistoryDataAggregatedFilesize}
   * @memberof PagespeedTestHistoryDataAggregated
   */
  filesize: PagespeedTestHistoryDataAggregatedFilesize;
  /**
   *
   * @type {PagespeedTestHistoryDataAggregatedLoadtime}
   * @memberof PagespeedTestHistoryDataAggregated
   */
  loadtime: PagespeedTestHistoryDataAggregatedLoadtime;
  /**
   *
   * @type {PagespeedTestHistoryDataAggregatedRequests}
   * @memberof PagespeedTestHistoryDataAggregated
   */
  requests: PagespeedTestHistoryDataAggregatedRequests;
  /**
   * Total number of returned results
   * @type {number}
   * @memberof PagespeedTestHistoryDataAggregated
   */
  results: number;
}

export function PagespeedTestHistoryDataAggregatedFromJSON(
  json: any,
): PagespeedTestHistoryDataAggregated {
  return PagespeedTestHistoryDataAggregatedFromJSONTyped(json, false);
}

export function PagespeedTestHistoryDataAggregatedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PagespeedTestHistoryDataAggregated {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    filesize: PagespeedTestHistoryDataAggregatedFilesizeFromJSON(
      json['filesize'],
    ),
    loadtime: PagespeedTestHistoryDataAggregatedLoadtimeFromJSON(
      json['loadtime'],
    ),
    requests: PagespeedTestHistoryDataAggregatedRequestsFromJSON(
      json['requests'],
    ),
    results: json['results'],
  };
}

export function PagespeedTestHistoryDataAggregatedToJSON(
  value?: PagespeedTestHistoryDataAggregated | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    filesize: PagespeedTestHistoryDataAggregatedFilesizeToJSON(value.filesize),
    loadtime: PagespeedTestHistoryDataAggregatedLoadtimeToJSON(value.loadtime),
    requests: PagespeedTestHistoryDataAggregatedRequestsToJSON(value.requests),
    results: value.results,
  };
}
