---
name: publish
on:
  release:
    types:
    - published
jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v4
      with:
        node-version: "19"
        registry-url: https://registry.npmjs.org
        cache: npm
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
