---
name: test
on:
  pull_request:
  push:
    branches:
    - gh-readonly-queue/**
    - master
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
        - "22"
        - "21"
        - "20"
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node }}
        cache: npm
    - run: npm ci
