---
name: test
on:
  pull_request:
  push:
    branches:
    - gh-readonly-queue/**
    - master
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
        - "19"
        - "18"
        - "16" # 17 does not work ¯\_(ツ)_/¯
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: npm
    - run: npm ci
